### PR TITLE
Add AMD Van Gogh ACP5x UCM files

### PR DESCRIPTION
**Pull request by tejasraman**
@sebanc As per the issue in the main brunch repo [brunch#1642](https://github.com/sebanc/brunch/issues/1642) Brunch currently does not have the necessary UCM configurations needed to support the ACP5x chipset used in AMD Van Gogh APUs.

This uses UCMs from Valve's packages in the AUR but they work on regular Linux kernels as well (not just Valve's special kernel - but only for 6.1). These have also been tested and working on non-Steam Deck Van Gogh systems.

(on Linux.....)

### CODE REVIEW

**Comment by MrHomebrew** [comment]
This is definitely a sought after fix to increase device compatibility, especially with the Steam Deck. As soon as this is asked to the unstable build I will give it a go. Hopefully this can be merged soon, great work by the entire community 👍

**Comment by tejasraman** [comment]
I'm still waiting for the PR to go through

**Comment by tejasraman** [comment]
Thanks so much @MrHomebrew!

**Comment by sebanc** [comment]
Thanks for the PR.

I will try to implement it when the first release of chromiumos kernel 6.1 is available.

**Comment by tejasraman** [comment]
afaik these should work with 5.15 too.... however, if 6.1 is needed, I'm willing to wait.

Thanks so much @sebanc

**Comment by sebanc** [comment]
I might be mistaken but my understanding is that sound would not work in linux on a steamdeck without some specific kernel patches which were included in kernel 6.1.

If you provide some evidence that sound works with the linux lts 5.15 kernel after installing those ucm files I can include this.

**Comment by MrHomebrew** [comment]
When I try to build from source with or without these changes I always get this

ImportError: No module named "google"

Leading to the build not finishing. I installed protobuf but for building dependencies all the Readme states us VM is needed.

If I could finish the build I would definitely test and see if sound is working. Idk why I keeping seeing this stupid error when trying to build and if I could just resolve it I would be able to test this sooner then later. Allowing me to report back my findings on if it allows audio.

**Comment by tejasraman** [comment]
@MrHomebrew you can install the UCMs manually into an existing Brunch install to test instead of building it. 

To do this, you need to download the acp5x folder from the UCM conf folder in my repo and move it to /usr/share/alsa/ucm2 (if there is a conf.d in that folder put it in there; if not put it in the folder path above) and run that command in the original issue to test. 

I personally don't have a steam deck to test with, so could you please try with 5.15 and report? These should work...

**Comment by MrHomebrew** [comment]
Will do asap, should have time in just a bit when I get home. Appreciate the time and effort @tejasraman with this along with everything done with brunch from sebanc.

**Comment by tejasraman** [comment]
Thanks so much @MrHomebrew

Hoping that it works :D

**Comment by MrHomebrew** [comment]
@tejasraman I am unable to write to the system/usr/share/ directory on chrome os. Tried with adb and with shell. Unless I am forgetting a command or step

**Comment by tejasraman** [comment]
Adb?

You need to use Sudo

**Comment by tejasraman** [comment]
@MrHomebrew 

Ok... You probably need 6.1 for these after all.

I guess you'll have to wait for 6.1 or build the kernel with CONFIG_SND_SOC_AMD_ACP5x. I'll ask @sebanc about this. 5.15 does support these UCMs with that building parameter.

I'm afraid that we'll have to wait on @sebanc about this.

Tejas

**Comment by tejasraman** [comment]
@sebanc an update: 5.15 does support ACP5x if built with CONFIG_SND_SOC_AMD_ACP5x (see [https://www.phoronix.com/news/Linux-5.15-Sound](https://www.phoronix.com/news/Linux-5.15-Sound) ).

**Comment by sebanc** [comment]
You can try to update to the below build and select kernel 6.1 in brunch settings:
https://github.com/sebanc/brunch-unstable/releases/tag/r109-unstable-20230205

If sound does not work, please attach here a copy of your "/var/log/messages" file.

**Comment by MrHomebrew** [comment]
Currently I am getting a boot loop with unstable-brunch build. Have not been able to update to the unstable build without this issue. 107 brunch stable boots only. Not sure why unstable builds will not boot yet, just reboots at this point in the picture.

Sorry not the clearest picture.
VideoCapture_20230210-184158

**Comment by guylamar2006** [comment]
Bootloop on 109 stable with default options.

**Comment by sebanc** [comment]
Could you try the latest brunch unstable build ?

Also, do you install chromeos on the ssd or sdcard ? And on which filesystem type ?

**Comment by MrHomebrew** [comment]
> Could you try the latest brunch unstable build ?
> 
> Also, do you install chromeos on the ssd or sdcard ? And on which filesystem type ?

I tested the latest and seemed to bootloop still. NTFS internal SSD partitioned.

And this is what I see before reboot once again
VideoCapture_20230211-132659

**Comment by sebanc** [comment]
I am a bit confused by this issue as I don't see a change I made which could cause this.

If you use 107 brunch stable and update only chromeos to r109 does it boot ?

**Comment by MrHomebrew** [comment]
> I am a bit confused by this issue as I don't see a change I made which could cause this.
> 
> If you use 107 brunch stable and update only chromeos to r109 does it boot ?

Anything above brunch 107 stable has had this issue with rebooting, even before you added 6.1 kernel was added to brunch.

I updated to chromeos 109 before without issue but whenever I went to even brunch unstable 108 this reboot issue would occur.

**Comment by sebanc** [comment]
Could you confirm that the release "Brunch r107 unstable 20221117" works and that "Brunch r107 unstable 20221128" does not ?
Otherwise, could you install a working brunch version and update to each brunch unstable release until it does not work and provide me with the first non-working version ?

**Comment by MrHomebrew** [comment]
> 

You read my mind, I was going to propose me testing from the working stable brunch 107 to the exact unstable build that brakes boot and causes the reboot loop. Will take some time but seeing as we both kind of had the same idea going to have to give it a try. Will report back as soon as I can with my findings.

**Comment by MrHomebrew** [comment]
@sebanc I found out which version starts to cause the constant rebooting I mentioned before.

Seems to be brunch unstable r108 from 2022,12,16. Link below to the specific build that has started the issue.

https://github.com/sebanc/brunch-unstable/releases/tag/r108-unstable-20221216

**Comment by sebanc** [comment]
Could you try the new brunch-unstable build when you have the time ?

**Comment by MrHomebrew** [comment]
> Could you try the new brunch-unstable build when you have the time ?

Great work, it has successfully booted in to ChromeOS on the latest Brunch Unstable 🙌 

No audio still and yes I am on kernel 6.1

Audio not working on 6.1 currently may be because brunch_configs is missing these two lines

CONFIG_SND_SOC_AMD_ACP5x=y
CONFIG_SND_SOC_AMD_VANGOGH_MACH=m

**Comment by tejasraman** [comment]
You need to download the audio UCMs again before trying...

**Comment by sebanc** [comment]
Great to see that it boots again :)

Those 2 kernel configs are correctly enabled in the kernel and I included tejasraman ucm files but audio in chromeos is a bit more complex than on linux.

Could you please attach here your chromeos "/var/log/messages" files ?

**Comment by guylamar2006** [comment]
[log.txt](https://github.com/sebanc/brunch-unstable/files/10726414/log.txt)

Here's my full /var/log/messages

**Comment by tejasraman** [comment]
@sebanc So I was looking around and I found a few things:
- In the log.txt, the acp5x drivers are loaded and an output (the headphone jack) is detected. I wonder why it's attaching to so many drivers... (even attaching to _both_ Renoir and Rembrandt audio drivers.
- The Steam Deck has a CS35L41 chipset, which has had Linux support since 5.17. ACP5x is mainly a coprocessor but still needed to get working audio on Steam Deck. I've looked into this and to get it working you _might_ need `CONFIG_SND_SOC_CS35L41_SPI` as a kernel option (y, not m). Not 100% sure on this, but this was what I found.




(Btw my knowledge of linux audio stuff may not translate to chromeos, so feel free to correct me if I'm wrong :) )

**Comment by guylamar2006** [comment]
and possibly CONFIG_SND_SOC_NAU8821=y

**Comment by tejasraman** [comment]
@guylamar2006 this is selected by CONFIG_SND_SOC_AMD_VANGOGH_MACH

**Comment by guylamar2006** [comment]
I looked through the 6.1 sources for the steam deck on the AUR. Here's some neptune/jupiter kernel parameters of interest that I found in the config file in the source code:


## Neptune stuff
##

# Doesn't build on latest tag, not used in neptune hardware (?)
CONFIG_SND_SOC_CS35L36=n
# Update this to =y to workaround initialization issues and deadlocks when loaded as module
# The cs35l41 / acp5x drivers in EV2 fail IRQ initialization with this set to =y, changed back
CONFIG_SPI_AMD=m

# Works around issues with the touchscreen driver
CONFIG_PINCTRL_AMD=y

CONFIG_JUPITER=m
CONFIG_SND_SOC_CS35L41=m
CONFIG_SND_SOC_CS35L41_SPI=m

CONFIG_SND_SOC_AMD_ACP5x=m
CONFIG_SND_SOC_AMD_VANGOGH_MACH=m
CONFIG_SND_SOC_WM_ADSP=m
CONFIG_SND_SOC_CS35L41=m
CONFIG_SND_SOC_CS35L41_SPI=m
# CONFIG_SND_SOC_CS35L41_I2C is not set
CONFIG_SND_SOC_NAU8821=m
# Enabling our ALS, only in jupiter branches at the moment
CONFIG_LTRF216A=m
##

LTRF216A apeears to be the ambient light sensor on the deck.

**Comment by sebanc** [comment]
I verified that all of the needed configs are correctly enabled and the log seems generally correct compared to what I could see on other linux dmesg for steamdeck but unfortunately the chromeos audio server crashes which is most likely due to outdated sof binaries (I cannot update them as chromeos still use alsalib 1.2.1.2).

I am still interested in solving this issue but I will need to think of a different approach.

**Comment by tejasraman** [comment]
Oh so it's Google being outdated. How typical, like how they use ancient kernels on Chromebooks (my school one is on 4.14 and I got it in 2021)... And I don't think replacing alsalib is a good idea

**Comment by sebanc** [comment]
Could you try the latest brunch unstable build with the below parameters selected in brunch settings:
- kernel: steamdeck
- kernel parameters: snd-intel-dspcfg.dsp_driver=1

**Comment by sebanc** [comment]
If someone has the time to try it, I would be interested to have feedback on the latest brunch-unstable build.

**Comment by guylamar2006** [comment]
[log.txt](https://github.com/sebanc/brunch-unstable/files/10833903/log.txt)

**Comment by sebanc** [comment]
Thanks for the latest log, I have hopefully identified one of the main reason sound was not working and fixed it in the latest build if you want to try it.

**Comment by guylamar2006** [comment]
Black screen right after chrome logo.

**Comment by sebanc** [comment]
I was able to have access to a steamdeck which made debugging much easier. Sound should work out of the box on the latest build with kernel 6.1.

I will close this PR once I have the confirmation that this issue is solved.

**Pull request closed without merging**
