### PR TITLE
Added missing kernel option from steam deck sources.

### PR DESCRIPTION
**Pull request by guylamar2006**
Removed duplicate PINCTRL_AMD=y and added missing steam deck kernel option from 5.15

### CODE REVIEW

**Comment by sebanc** [comment]
The config "CONFIG_SND_SOC_CS35L41=m" is already enabled in the kernel by selecting "CONFIG_SND_SOC_CS35L41_SPI=m".

Have you tried the latest build, sound still does not work ?

**Comment by guylamar2006** [comment]
I've tried the latest build and put in the kernel option, some of the config options don't get picked up when I sudo modprobe configs ; cp /proc/config.gz ~/Downloads/ : gunzip config.gz ; nano config. Maybe some modules are missing. I just gotta find out which modules in the sources Kconfig point to the missing kernel options with grep.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sebanc** [comment]
I let you verify but as far as I can tell the needed configs are enabled. 

Could you attach the /var/log/messages file here ?

**Comment by guylamar2006** [comment]
[log.txt](https://github.com/sebanc/brunch-unstable/files/10785177/log.txt)
Here's the latest log using steamdeck kernel.

**Comment by sebanc** [comment]
I added some sound configs in the latest build if you want to try it.

**Comment by guylamar2006** [comment]
[log.txt](https://github.com/sebanc/brunch-unstable/files/10799833/log.txt)

Latest log, no sound.

**Comment by sebanc** [comment]
I was able to have access to a steamdeck which made debugging much easier. Sound should work out of the box on the latest build with kernel 6.1.

**Pull request closed without merging**
